
name: '$(date:yyyyMMdd)$(rev:-rr)'

trigger:
  batch: true
  branches:
    include:
    - master


stages:
- stage: build_ci
  displayName: "Building for CI"
  dependsOn: []
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-2022'

    variables:
      buildConfiguration: 'Release'
      isPre: true
      Major: 1
      Minor: 0
      Patch: $(Build.BuildId)
      PackageVersionType: "" #"-preview-$(Build.BuildNumber)"
      PackageVersion: $(Major).$(Minor).$(Patch)$(PackageVersionType)

 
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 5.x
        #checkLatest: false # Optional
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: 'src/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
        versioningScheme: byEnvVar
        versionEnvVar: PackageVersion
      displayName: 'dotnet pack $(buildConfiguration)'

        
    - publish: $(Build.ArtifactStagingDirectory)

    - task: NuGetCommand@2
      displayName: 'nuget push'
      inputs:
        command: 'push'
        feedsToUse: 'select'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'DL/DLF'
        vstsFeed: 'DL/DLF'
        versioningScheme: 'off'
        allowPackageConflicts: true